import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {validatePlan,validateFiles,safeArtifactPath,splitPolicies,runFileArm} from '../src/orchestration/live-file-workers.mjs';
const plan=()=>({integrationInstructions:'Use independent modules.',tasks:[{id:'a',description:'A',paths:['a.py'],dependsOn:[]},{id:'b',description:'B',paths:['b.py'],dependsOn:[]}]});
test('plan rejects cycle, unknown dependencies, duplicate and nested ownership',()=>{
 for(const change of [p=>{p.tasks[0].dependsOn=['b'];p.tasks[1].dependsOn=['a'];},p=>p.tasks[0].dependsOn=['x'],p=>p.tasks[1].paths=['a.py'],p=>p.tasks[1].paths=['a.py/nested'],p=>p.tasks[1].id='a']){const p=plan();change(p);assert.throws(()=>validatePlan(p));}
});
test('paths reject traversal and privileged metadata',()=>{for(const p of ['../secret','/tmp/a','a/../b','a\\b','.git/config','a//b'])assert.throws(()=>safeArtifactPath(p));});
test('files must match exact ownership and all assigned files',()=>{assert.throws(()=>validateFiles({summary:'x',files:[]},['a']));assert.throws(()=>validateFiles({summary:'x',files:[{path:'x',content:''}]},['a']));assert.throws(()=>validateFiles({summary:'x',files:[{path:'a',content:''},{path:'a',content:''}]},['a']));});
test('threshold policy abstains on insufficient evidence and preserves 0 probability',()=>{assert.deepEqual(splitPolicies({beneficial:{noul:0},evidence:{choice:'sufficient'}}).map(x=>x.action),['single','single','single']);assert.ok(splitPolicies({beneficial:{noul:.9},evidence:{choice:'insufficient'}}).every(x=>x.action==='collect_evidence'));assert.deepEqual(splitPolicies({beneficial:{noul:.7},evidence:{choice:'sufficient'}}).map(x=>x.action),['split','split','single']);assert.throws(()=>splitPolicies({beneficial:{noul:NaN},evidence:{choice:'sufficient'}}));});
test('split runs disjoint workers concurrently and materializes only validated files',async()=>{const dir=mkdtempSync(join(tmpdir(),'jev-arm-'));let active=0,max=0;try{const result=await runFileArm({plan:plan(),brief:[],mode:'split',outputDir:join(dir,'out'),call:async req=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,10));active--;return {response:{summary:'unexecuted',artifacts:req.task.paths,observed_checks:[],blockers:[],uncertainty:['unexecuted'],files:req.task.paths.map(path=>({path,content:path}))}};}});assert.equal(result.status,'completed');assert.equal(max,2);assert.equal(readFileSync(join(dir,'out/a.py'),'utf8'),'a.py');}finally{rmSync(dir,{recursive:true,force:true});}});
test('failed stage drains in-flight worker and prevents dependent dispatch',async()=>{const dir=mkdtempSync(join(tmpdir(),'jev-drain-'));const p=plan();p.tasks.push({id:'c',description:'C',paths:['c.py'],dependsOn:['a','b']});let drained=false;const labels=[];try{const result=await runFileArm({plan:p,brief:[],mode:'split',outputDir:join(dir,'out'),call:async req=>{labels.push(req.task.id);if(req.task.id==='a')throw new Error('fail');await new Promise(r=>setTimeout(r,10));drained=true;return {response:{summary:'ok',artifacts:['b.py'],observed_checks:[],blockers:[],uncertainty:[],files:[{path:'b.py',content:'b'}]}};}});assert.equal(result.status,'failed');assert.equal(drained,true);assert.deepEqual(labels,['a','b']);}finally{rmSync(dir,{recursive:true,force:true});}});
test('dependent worker receives completed files; single receives all ownership',async()=>{const dir=mkdtempSync(join(tmpdir(),'jev-dep-'));const p=plan();p.tasks[1].dependsOn=['a'];try{await runFileArm({plan:p,brief:[],mode:'split',outputDir:join(dir,'split'),call:async req=>{if(req.task.id==='b')assert.equal(req.completedFiles[0].path,'a.py');return {response:{summary:'ok',artifacts:req.task.paths,observed_checks:[],blockers:[],uncertainty:[],files:req.task.paths.map(path=>({path,content:''}))}};}});let n=0;await runFileArm({plan:p,brief:[],mode:'single',outputDir:join(dir,'single'),call:async req=>{n++;assert.equal(req.task.paths.length,2);return {response:{summary:'ok',artifacts:req.task.paths,observed_checks:[],blockers:[],uncertainty:[],files:req.task.paths.map(path=>({path,content:''}))}};}});assert.equal(n,1);}finally{rmSync(dir,{recursive:true,force:true});}});

test('no-tools output rejects invented checks and mismatched artifact receipts',()=>{const good={summary:'ok',files:[{path:'a',content:'x'}],artifacts:['a'],observed_checks:[],blockers:[],uncertainty:['unexecuted']};assert.equal(validateFiles(good,['a']).length,1);assert.throws(()=>validateFiles({...good,observed_checks:[{passed:true}]},['a']));assert.throws(()=>validateFiles({...good,artifacts:['b']},['a']));});

test('projected live arm filters unrelated files and supports serial split',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'jev-v3-'));const p=plan();p.tasks.push({id:'c',description:'C',paths:['c.py'],dependsOn:['a']});let active=0,max=0;const events=[];
 try{const r=await runFileArm({plan:p,brief:['retain all constraints'],mode:'split',inputMode:'projected',maxConcurrency:1,outputDir:join(dir,'out'),record:async e=>events.push(e),call:async req=>{
  active++;max=Math.max(max,active);assert.equal(req.inputVersion,'worker-input-v3');assert.equal(req.plan,undefined);
  if(req.task.id==='c')assert.deepEqual(req.completedFiles.map(f=>f.path),['a.py']);
  active--;return {response:{summary:'ok',artifacts:req.task.paths,observed_checks:[],blockers:[],uncertainty:[],files:req.task.paths.map(path=>({path,content:'generated'}))}};
 }});assert.equal(r.status,'completed');assert.equal(max,1);assert.ok(events.filter(e=>e.event==='worker_input_prepared').every(e=>Number.isFinite(e.input_preparation_ms)));}finally{rmSync(dir,{recursive:true,force:true});}
});
